server {
    listen 80;
    server_name _;

    # root points to the built files we’ll copy to /usr/share/nginx/html
    root /usr/share/nginx/html;
    index index.html;

    # serve static assets
    location /assets/ {
        try_files $uri /index.html;
        access_log off;
        expires 30d;
    }

    # single-page-app fallback (Vue router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # basic gzip for text assets
    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/xml+rss application/xml text/javascript;
}
